### ISSUE TITLE
Score duplication when each player logs the same game

### ISSUE THREAD

**Issue by mankalas** [yumoose/skirmish#33]
### Issue
Player A and Player B play against each other.
Afterward, each player logs the same game, then confirms the issues, resulting in two confirmed identical games. Also, that means that the score has been update twice.

### Suggestion
When a player logged a game for a match, the other player can't log a game: just confirm it.

### Example
https://skirmish.online/leagues/3
![skirmish](https://user-images.githubusercontent.com/6638185/52455470-100eef80-2bb5-11e9-89f0-eade19d22561.png)

**Comment by yumoose** [comment]
Another solution would be to allow player's the ability of deleting their own logged games that have not been confirmed, rather than locking down the logging of games. And another, to add a disclaimer on the log screen if there is an unconfirmed game between the two players already.

I think both of these together would be sufficient enough to both stop users making mistakes, and help them patch things up themselves when they do.

**Comment by yumoose** [comment]
Raised the above as two issues to help guard against, and help remedy mistakes in logged game duplicates.
